// axios
import axios from 'axios'

const baseURL = 'http://back.clicking.com/api'

// replace future for localStorage
const token = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMTA5NmI5NWQzYTIzMGEwYzk3NjhhZjFkOWNlNzAxNjliN2MxZjljNjM1NmQwNTQwNDQ2ODVmYzIxOGU0ZjNiNzM5MDdjNzc1NzZjZDBlZjAiLCJpYXQiOjE2MDE2MDEzNzIsIm5iZiI6MTYwMTYwMTM3MiwiZXhwIjoxNjE3MzI2MTcyLCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.LE0nZsNOQ7uXTXMssAlOuHgEihHqXU4QF6qN9X01nDfPczhn1ACznbcVuAQFacFAXDQrujpjcMZt0y-uAsGWUsOkDS3qRy-myXUPWX5lFwSo9rTkCmbFl1a0qjlcrT-5MbPCHV4ibB-0illqLfqpuRuaxJf-A9x1BNSglBFGEkTBBdJpWmuYfpl6bxi_kthiiSnw2dVlRu4lo3BpXtUlRMfyFzoYr-qGPzfne_Quq2NeDPBly0N4Nwlls_8EhDj2WSSwMIwMOQvvViGrftLMV6Y0_K4nJ_8Q4bsPHR8fKyP-HI2NaTjf96LEmFVOiHTYNTwjDJf-toxWwOhvuP8sKKXNoaKudoeugIx6tIhnCpC5tfRAQ5neOP_p0fk-5JWWXlZVeP-AIwc2pTrOUDmZbBjpEllyu6YeO9jd1GUATTAepGi7xEHcexNkDY60vwVIE3XdSPfKJOk1CTq3fzeyWNZP86SlWZy7DHJiKxVSpZ4zEUzN2WGprnIRlw-VXHzdlhuajp93H3HWZU0etbLOiNZMs32GWPxJSTDzbG6Di8ceYKZrwdeCL75_U_mWSkmrBMicGq41ZxpQ-MS4B_JatwGXPyn9TgBMHP62QM-jdOsmLe3qcYuDSc1QkCENVD2ZMsDHrYrPAaCWArj9nqHVMFsMItblYW9dfXQMPzeLIm8'

export default axios.create({
  baseURL,
  headers: {
      Authorization: token,
      'Content-Type': 'application/json',
  }
  // You can add your headers here
})
