// axios
import axios from 'axios'

const baseURL = 'http://back.clicking.com/api'

// replace future for localStorage
const token = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiNGYxZDU2ZDA0Njk4YTJiMmRjNTJmMDM0ZGJiODFjM2VjODU1NjM0YjFlMmVmYjViNTRkYmJhODNkOGFlYTY3N2JjYmYyMDFkMjhkZTJjYzYiLCJpYXQiOjE2MDE2NDA1ODQsIm5iZiI6MTYwMTY0MDU4NCwiZXhwIjoxNjE3MzY1Mzc1LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.PRQceswTbJZh9sbReO8Hx5os5_S9w2NYYb_eakryWrkJDdfFQ3sUbw7rZsvnh0tB6TvMy6u2_EdjoPyICQgkn1tx90AiNuehEX3teLpX22zAzydxou7R1QQGTpt4dauwCJyq8twnNy_bHb8kvre4fQQDVHN5MIevFJ8OXH78wZSc31AmfGaAIIuehaETpkgExNq0c0t2iw9KpE1avRhxZhCcUlcikZadA5kqmZ5ly4fuktiUEihwQ8XFPOX9SdfNT2xlc9HEatYluxTNvil0nGBXhdT4srHgiGmEtVxXRb2PwI-LNpW1RDWc8NKRdP8wcDJjYFodo_eWuHpCfkh13yW7tcWldMZkLbnzSMMr3xuzJ482JkbjPbO6n-BzZL7KxPhnbMPhbwk4lux_zdi0wCUD-94FUxkk4TG-AQ7IHIT5bFWWlad1IkO-rayjZJ9Bo0ZwYCV7laH3RDn1Oyzdrf7CHH2dReaLNm6s3_PKDMzv7e1vpr_bqe7OkegOBr1IZhtkqjeWmaGgwsb6WQotpDah-0Nfwn-qOCjplIvM-slCqZ9SwrQkvQkMNp42hMRsY_2CP19MW4uOGGQnIwvOluMfSbUgcKvCHE_aekhxtpRQY3laEPxIbsIbQykj3SbdOj00qmr5POw0JdlqM17BeEAjptpx9Ym6CmpOptW-2aw'

export default axios.create({
  baseURL,
  headers: {
      Authorization: token,
      'Content-Type': 'application/json',
  }
  // You can add your headers here
})
